name: Test

on:

  push:
    branches: [ 'master' ]

  pull_request:
    branches: [ 'master', 'release-*' ]

jobs:

  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for .codecov.yaml
        id: codecov-enabled
        uses: andstor/file-existence-action@v1
        with:
          files: .codecov.yaml

      - if: steps.codecov-enabled.outputs.files_exists == 'true'
        name: Produce Go Coverage
        run: echo '::set-env name=COVER_OPTS::-coverprofile=coverage.txt -covermode=atomic'

      - name: Test
        run: go test -race $COVER_OPTS ./...

      - if: steps.codecov-enabled.outputs.files_exists == 'true'
        name: Codecov
        uses: codecov/codecov-action@v1
